import { defineConfig } from "vite"
import vue from "@vitejs/plugin-vue"
import dts from "vite-plugin-dts"

// ref: https://github.com/wuruoyun/vue-component-lib-starter
import { name } from "./package.json"

export default defineConfig({
    plugins: [
        vue(),
        dts({
            outDir: "./dist/types",
        }),
    ],
    build: {
        outDir: "./dist",
        lib: {
            entry: "./src/index.ts",
            name: name,
            formats: ["es"],
            fileName: (format) => `${name}.${format}.js`,
        },
        rollupOptions: {
            // external modules won't be bundled into your library
            external: ["vue", "vuetify"],
        },
        emptyOutDir: false, // to retain the types folder generated by tsc
    },
})
