import {defineConfig} from 'vite';
import vue from '@vitejs/plugin-vue';

// ref: https://github.com/wuruoyun/vue-component-lib-starter
import {name} from './package.json';

export default defineConfig({
    root: 'demo',
    plugins: [vue()],
    build: {
        outDir: '../dist',
        lib: {
            entry: '../src/index.ts',
            name: name,
            formats: ['es'],
            fileName: (format) => `${name}.${format}.js`,
        },
        rollupOptions: {
            // external modules won't be bundled into your library
            external: ['vue', 'vuetify'],
            output: {
                // disable warning on src/index.ts using both default and named export
                exports: 'named',
                // Provide global variables to use in the UMD build
                // for externalized deps (not useful if 'umd' is not in lib.formats)
                globals: {
                    vue: 'Vue',
                    vuetify: 'Vuetify',
                },
            },
        },
        emptyOutDir: false, // to retain the types folder generated by tsc
    },
});
